import "NullableString.idl";
import "Models.DateFormat.idl";
import "Models.CurrencyFormat.idl";
import "Models.Account.idl";
import "Models.Payee.idl";
import "Models.PayeeLocation.idl";
import "Models.CategoryGroup.idl";
import "Models.Category.idl";
import "Models.MonthInfo.idl";
import "Models.Transaction.idl";

namespace YnabApi
{
    namespace Models
    {
        [bindable]
        [default_interface]
        runtimeclass Budget
        {
            Budget();
            String Id;
            String Name;
            apicc.NullableString LastModifiedOn;
            DateFormat DateFormat;
            CurrencyFormat CurrencyFormat;
            Windows.Foundation.Collections.IVector<Account> Accounts;
            Windows.Foundation.Collections.IVector<Payee> Payees;
            Windows.Foundation.Collections.IVector<PayeeLocation> PayeeLocations;
            Windows.Foundation.Collections.IVector<CategoryGroup> CategoryGroups;
            Windows.Foundation.Collections.IVector<Category> Categories;
            Windows.Foundation.Collections.IVector<MonthInfo> Months;
            Windows.Foundation.Collections.IVector<Transaction> Transactions;
        }
    }
}
