import "Models.Error.idl";
import "Models.Budget.idl";

namespace YnabApi
{
    namespace Models 
    {
        [bindable]
        [default_interface]
        runtimeclass BudgetsResponse
        {
            BudgetsResponse();
            Error Error;
            Windows.Foundation.Collections.IVector<Budget> Budgets;
         }
    }
}
