import "NullableString.idl";
import "Models.DateFormat.idl";
import "Models.CurrencyFormat.idl";

namespace YnabApi
{
    namespace Models
    {
        [bindable]
        [default_interface]
        runtimeclass BudgetSummary
        {
            BudgetSummary();
            String Id;
            String Name;
            apicc.NullableString LastModifiedOn;
            DateFormat DateFormat;
            CurrencyFormat CurrencyFormat;
        }
    }
}
