import "NullableString.idl";

namespace YnabApi
{
    namespace Models
    {
        [bindable]
        [default_interface]
        runtimeclass Error
        {
            Error();
            String Id;
            String Name;
            String Detail;
        }
    }
}
